name: Publish Release

on:
  push:
    tags:
      - 'release/v*'

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release

    steps:
    - name: "Install StepSecurity Action"
      id: step_security
      uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
      with:
        egress-policy: audit

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install

    - name: Build the package
      run: poetry build

    - name: Publish to PyPI
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
      run: poetry publish

    - name: Create GitHub Release
      uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1
      with:
        artifacts: |
          dist/*.tar.gz
          dist/*.whl
        token: ${{ secrets.GITHUB_TOKEN }}
